import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  profileContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    alignItems: "center",
    width: "100%",
    gap: 30,
  },
  profileHeader: {
    alignItems: "flex-start",
    width: "100%",
  },
  profileTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "black",
    textAlign: "left",
  },
  profileInfoContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingVertical: 45,
  },
  profileInfoBox: {
    backgroundColor: "#0BAF9A",
    width: "100%",
    height: 120,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    gap: 20,
    paddingLeft: 20,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 50,
    backgroundColor: "white",
  },
  profileDetails: {
    alignItems: "flex-start",
    justifyContent: "center",
  },
  userNameStyle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  userRecordNoStyle: {
    fontSize: 17,
    color: "#ffffff",
    fontWeight: "semibold",
  },
  infoStyle: {
    width: "100%",
    paddingVertical: 7,
    gap: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  menuContainer: {
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    textAlign: "center",
    width: "100%",
  },
  btnStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "transparent",
    borderRadius: 10,
    paddingVertical: 5,
    marginBottom: 1,
    gap: 10,
    width: "100%",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    justifyContent: "space-between",
    width: "100%",
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  arrowContainer: {
    backgroundColor: "lightgray",
    padding: 2,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  BuatPendaftaranBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    padding: 10,
    backgroundColor: "#0BAF9A",
    borderRadius: 6,
    borderColor: "yellow",
    borderWidth: 0.5,
  },
  logoutText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    paddingVertical: 4,
  },

  dropdown: {
    // margin: 16,
    height: 50,
    borderWidth: 1,
    borderColor: "#0BAF9A",
    borderRadius: 5,
    padding: 10,
    paddingLeft: 25,
    width: "100%",
    fontSize: 16,
    backgroundColor: "#FAFAFA",
    elevation: 2,
    color: "lightgrey",
  },
  icon: {
    marginRight: 6,
  },
  item: {
    padding: 17,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textItem: {
    flex: 1,
    fontSize: 16,
    color: "black",
  },
  placeholderStyle: {
    fontSize: 16,
    color: "lightgrey",
  },
  selectedTextStyle: {
    fontSize: 16,
    color: "black",
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
  scheduleContainer: {
    flexDirection: "row",
    marginTop: 20,
    padding: 15,
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
  },
  scheduleTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0BAF9A",
  },
  scheduleItem: {
    
    fontSize: 14,
    color: "#333",
    marginVertical: 2,
  },
  noScheduleText: {
    fontSize: 14,
    color: "red",
  },
  dayItem: {
    padding: 12,
    borderRadius: 8,
    width: 80,
    alignItems: "center",
    marginRight: 8,
  },
  dayText: {
    color: "#fff",
    fontWeight: "bold",
  },
  daysScrollContainer: {
    flexDirection: "row",
  },
});
